export const PENDING = 'PENDING';
export const LOAD_ASTEROIDS = 'LOAD_ASTEROIDS';
export const LOAD_SINGLE_ASTEROID = 'LOAD_ASTEROID';
export const CHANGE_DISTANCE_TYPE = 'CHANGE_DISTANCE_TYPE';
export const ADD_TO_DESTRUCT = 'ADD_TO_DESTRUCT';
export const DESTRUCT_ASTEROIDS = 'DESTRUCT_ASTEROIDS';

